### ISSUE TITLE
can I use with firebase function ?

### ISSUE THREAD

**Issue by amitbravo** [jamiechapman/simple-onesignal#3]
I want to write a firebase cloud function to send push notifications to android /ios devices ? ( app built with react native , firebase as backend )

**Comment by ghost** [comment]
Works for me fine.

**Comment by adirzoari** [comment]
@datureezy  do you have example to send one signal notification with firebase function?

**Comment by ghost** [comment]
first you have to be a paying member on firebase to use 3rd party node packages and connect them to firebase cloud functions.

install in your desired push notification company's solution. i use onesignal.

on my real time db, i created a cloud trigger where if a new value gets created on a node, it's going to run a cloud function that talks to my push notification library in creating a token, etc, and once that's done, it does a query to find the push token of the user i need to send a message to, and then, BAM! a push notification gets sent in blazing speed.

other than that, the game is to be sold, not told.

hope i gave you enough to run with to get this integrated.

**Comment by adirzoari** [comment]
Can u publish the code with onesignal? I used this library simple onesignal but i dont have indication for sucess/failed notification
