### ISSUE TITLE
Plugin crashes when receiving a bad response from OneSignal

### ISSUE THREAD

**Issue by nabilfreeman** [jamiechapman/simple-onesignal#4]
OneSignal went down today and some of the timeouts ended up causing this plugin to crash, I believe because it always expects a proper response from their API.

The error was: `SyntaxError: Unexpected token < in JSON at position 0` at line https://github.com/jamiechapman/simple-onesignal/blob/fc4d795afe7551d0791614af9d822e8068a21713/src/index.js#L110

I think there is easy easy fix here, which is to catch unhandled exceptions and then resolve the callback with an error like `Failed to get a response from OneSignal.`

@jamiechapman - can I make a PR to handle these errors?

**Comment by jamiechapman** [comment]
Good catch! Sure, if you send over a pull request I'm happy to merge it.

**Comment by nabilfreeman** [comment]
Hey @jamiechapman, sorry for taking so long with this. For a while, the issue was happening for us so intermittently that I kept putting it off.

Looks like OneSignal are having issues again (we are seeing this occur frequently again during UTC nighttime for the past fortnight) so I'm going to put in a PR today.
