### ISSUE TITLE
Adding Headers and Data

### ISSUE THREAD

**Issue by in-techouse** [jamiechapman/simple-onesignal#6]
I want to add `Headers` and `Data` to the Notification. 

I managed to did this locally in my application while performing some changes in Your package. 
So can You please add those changes in this `npm module` or You can also add me as a contributor and I can make changes to add `Headers` and `Data` in the notification.

**Comment by jamiechapman** [comment]
Hi @team-dev-man, sure. Just send a PR and I can add headers into this repo. I closed the #7 PR request as it was only a change to the README.
